// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDceA0QfV_AAzhg4vm-k8q-X1vfWf85wX0',
    appId: '1:77030948186:web:05dbd6ebece22da01dc763',
    messagingSenderId: '77030948186',
    projectId: 'chat-base-5ce38',
    authDomain: 'chat-base-5ce38.firebaseapp.com',
    storageBucket: 'chat-base-5ce38.appspot.com',
    measurementId: 'G-82MJBJHJR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3im8umfmJ6ZyuAZ60HoPXIb-qiXvcZ1A',
    appId: '1:77030948186:android:4e85bef3473253a51dc763',
    messagingSenderId: '77030948186',
    projectId: 'chat-base-5ce38',
    storageBucket: 'chat-base-5ce38.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDceA0QfV_AAzhg4vm-k8q-X1vfWf85wX0',
    appId: '1:77030948186:web:55f86419400c13811dc763',
    messagingSenderId: '77030948186',
    projectId: 'chat-base-5ce38',
    authDomain: 'chat-base-5ce38.firebaseapp.com',
    storageBucket: 'chat-base-5ce38.appspot.com',
    measurementId: 'G-756E2KEPNZ',
  );
}
